### ISSUE TITLE
Add travis job for ubuntu 20.04

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#1071]
As suggested by @cquike in #1062, it would be good to test a build on Ubuntu 20.04 in CI.

**Comment by rtobar** [comment]
Related to this, mind you that Travis recently changed their pricing model, and OSS projects need to be assessed on a case-by-case basis. We at ICRAR have already hit our limit, and are in a bit of a struggle between porting to a different service (e.g., GitHub actions) or continue waiting for a positive response from Travis (it's been a week since we contacted them) to allow us continuing using their service for free.

**Comment by gijzelaerr** [comment]
we are currently testing on 18.04 and 20.04 https://github.com/casacore/casacore/blob/master/.github/workflows/linux.yml#L18
