### ISSUE TITLE
Baseline length using taql

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/casacore#1105]
Hello everyone,

I was reading NOTE 199 and I noticed that to calculate the baseline length UVW[:2] values are used along with GROUPBY ANTENNA1, ANTENNA2. I have a couple of questions that I would like to address here:

- UVW coordinates are projections given the position of the couple of antennas and the object. In that sense, I can have different UVW coordinates for the same baseline, on which using GROUPBY, the last UVW coordinate will be chosen. Can I query the ANTENNA table and get the POSITION column and get the baselines from there?

- I have done this latter and I am getting different results in comparison to using UVW coordinates, it that because x,y,z antenna positions are phase reference positions? It is possible to get the baseline length using the ANTENNA table?

Best regards,

**Comment by gervandiepen** [comment]
Hello Miguel,

You can use the foillowing command in TaQL:
    select NAME,sqrt(sumsqrs([select POSITION from ANTENNA] -
resize(POSITION,[[select gcount() from ANTENNA][0],3],1),1)) from ANTENNA

A short explanation because the command might look a bit complicated.
- The first inner select gets the POSITION of all antennae from which the
POSITION in each row is subtracted (to get all baselines per row).
- The second inner select gets the nr of antennae. It is used in the resize
function (using mode 1 to copy the values) to make the arrays in the
subtraction the same shape. TaQL does not do axes broadcasting as numpy
does.
- The sumsqrs function calculates x^2+y^2+z^2 for each baseline (it
collapses axes 1), whereaftere sqrt gives you the length.

The result is a matrix of baseline lengths.

Cheers, Ger

**Comment by gervandiepen** [comment]
Hello Miguel,

Can this issue be closed?

Cheers, Ger
