### ISSUE TITLE
Release casacore 2.0.2?

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#125]
I noticed in the last week's release 4.4 of NRAO Casa that its CMakeLists.txt contains the line
```
casa_find( CASACORE
           VERSION 2.0.2
```
( see https://svn.cv.nrao.edu/view/casa/branches/release-4_4/code/CMakeLists.txt?revision=33147 )

It would be nice if this release could actually exist and be compatible with Casa 4.4. 

This may need some ad-hoc fix for #113 since the requested functionality was already implemented on a fork of casacore ( https://svn.cv.nrao.edu/view/casa/branches/release-4_4/casacore/ ).

**Comment by gervandiepen** [comment]
Jim is still making changes in his new reformOrResize function. We should
wait until he has finished it.
Furthermore, NRAO requested to lower the wcslib version to 4.17 because
that is what they use. Is there a particular reason why 4.20 is the minimum
in the current CMakeLists.txt?
Ger

On Mon, Jun 22, 2015 at 9:26 PM, Tammo Jan Dijkema <notifications@github.com

**Comment by tammojan** [comment]
> NRAO requested to lower the wcslib version to 4.17 because that is what they use. Is there a particular reason why 4.20 is the minimum in the current CMakeLists.txt?

See #122. I'll set the milestone to 2.0.2

**Comment by JimNrao** [comment]
We're bumping into the 2.0.2 issue as well while trying to get our jenkins up and building directly using the latest code from github.  We have historically bumped up a low-order version number on CasaCore when changes in it are necessary for the current version of CASA to build (e.g., if a new method is added then users need to refresh not only CASA but also CasaCore).  That's how we've been doing things for a long while, but maybe it's not the best way.  To support that way, if that's the way we go, would require that any change which changed the API would need to bump the version, probably in the third component (e.g., 2.0.0 --> 2.0.1, etc.).

How do other projects build with CasaCore handle this?

**Comment by tammojan** [comment]
> How do other projects build with CasaCore handle this?

I think NRAO Casa is the only project that relies on the newest features of casacore. If LOFAR uses a newer feature, there is always a backup for older versions of casacore.

I don't think any API change justifies a version bump. Rather, I think the goal should be that Casa releases should build against casacore releases. The development version of Casa could use the development version (the master branch) of casacore. 

This scheme would probably require a new casacore release for every Casa release. (But there could be more casacore releases.)

What do you think of this?

**Comment by dpetry** [comment]
Hi,
IMHO we need to have something rapid which permits new code in casacore
to become available to other NRAO/ESO/NAOJ CASA developers within 24 h
of the commit to the repository.
I.e. when developer A finds that his/her code is good for use/testing by others
and puts it into the repository,
then developer B should not have to wait more than 24 h to get at the new code.

I think your suggestion to use the master branch would achieve that, wouldn't it?

I am also new to github. Could you describe the typical path a code change from
developer A to the rest of the team would take?

Thanks!

Dirk

On 06/27/2015 08:35 PM, Tammo Jan Dijkema wrote:
>     How do other projects build with CasaCore handle this?
>
> I think NRAO Casa is the only project that relies on the newest features of casacore. If LOFAR uses a newer feature, there is always a backup for older versions of casacore.
>
> I don't think any API change justifies a version bump. Rather, I think the goal should be that Casa releases should build against casacore releases. The development version of Casa could use the development version (the master branch) of casacore.
>
> This scheme would probably require a new casacore release for every Casa release. (But there could be more casacore releases.)
>
> What do you think of this?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/casacore/casacore/issues/125#issuecomment-116114682>.
>


-- 
Dr. Dirk Petry, ALMA Regional Centre,
ESO, Karl-Schwarzschild-Strasse 2, 85748 Garching,
Germany, Phone: +49 89 3200-6511, Fax: -6358

**Comment by tammojan** [comment]
> Could you describe the typical path a code change from developer A to the rest of the team would take?

I have to think about this a bit. Everything is online and public, so there is no technical limitation to do this. But we have to come up with a practical scheme. In fact, the shared-repository model may be better depending on the use cases. Let's discuss this next week when you're at Astron.

**Comment by JimNrao** [comment]
I think the only delay in the process is the time between a pull request 
being made and it being accepted, then merged into the master.  The 
actual merging should be fairly quick, so the time is probably spent 
just evaluating the pull request.  Once it's in the master, the next 
fetch from the master branch will have it.

On 6/28/2015 5:00 AM, Tammo Jan Dijkema wrote:
>
>     Could you describe the typical path a code change from developer A
>     to the rest of the team would take?
>
> I have to think about this a bit. Everything is online and public, so 
> there is no technical limitation to do this. But we have to come up 
> with a practical scheme. In fact, the shared-repository model may be 
> better depending on the use cases. Let's discuss this next week when 
> you're at Astron.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/125#issuecomment-116255957>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtGbzfLf1BiQfitTnpAyJwETvChsgks5oX8tmgaJpZM4FJOTj.gif
>


-- 
Jim Jacobs

**Comment by tammojan** [comment]
Agreed. I wonder if there is a need to use each other's code before it's ripe enough to become a pull request. The solution for this case would probably be a branch on the main repo.

**Comment by dpetry** [comment]
The CASA philosophy was always to commit only when all tests pass.
But at that point all developers should get the delta quickly such that they notice problems early.
Fiddling with branches, creating and merging them frequently, is asking for trouble
and causes additional work.

On 06/29/2015 07:19 PM, Tammo Jan Dijkema wrote:
> Agreed. I wonder if there is a need to use each other's code before it's ripe enough to become a pull request. The solution for this case would probably be a branch on the main repo.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/casacore/casacore/issues/125#issuecomment-116767084>.
>


-- 
Dr. Dirk Petry, ALMA Regional Centre,
ESO, Karl-Schwarzschild-Strasse 2, 85748 Garching,
Germany, Phone: +49 89 3200-6511, Fax: -6358

**Comment by gijzelaerr** [comment]
@tammojan Looks like there are no 2.0.2 issues left, shall we make a release?

**Comment by tammojan** [comment]
I'll discuss this tonight with @jimnrao, since this is a release specifically for NRAO casa compatibility.

**Comment by tammojan** [comment]
For LOFAR a patch release is quite urgent to get #141 into the system.

@juliantaylor and @jimnrao : how far are you along with the casa build? Does it make sense to wait for that?

**Comment by juliantaylor** [comment]
you need to make a release to get it into the system?
for casa we currently don't rely on any

**Comment by tammojan** [comment]
I think our policy is to build lofar releases on casacore releases, and the lofar trunk on the casacore trunk. Rethinking this, I don't think the 2.0.1 release had the issue that was fixed in #141, so actually a release shouldn't be very urgent. I'll recheck with @apschoenmakers .

**Comment by juliantaylor** [comment]
ups misclicked 
we are currently are trying to build and test against git master and don't need any specific releases.
There are still a couple unresolved test failures and many of the longer regressions haven't run yet, so there might still be more buggy code in master you may not want to release, but resolving this will still take some time.

**Comment by tammojan** [comment]
I suppose you would want to release a casacore once it compiles with the casa trunk? That would be a major milestone.

**Comment by juliantaylor** [comment]
the next casa release is due sometime in the 4. quarter and we bundle casacore with it so there is no separate release.
which casacore we will be using for the next release is still somewhat open, I think the current plan is to at some point branch casacore and just add necessary bugfixes to that from master until release.
Our feature freeze is 3. august.

**Comment by tammojan** [comment]
> the next casa release is due sometime in the 4. quarter and we bundle casacore with it so there is no separate release.

Then I suppose it would make sense to make a casacore release which corresponds to the casacore that you are releasing?

**Comment by juliantaylor** [comment]
I can't really answer that, maybe @JimNrao can say more on that?
I don't think the casacore we released and then googlecode casacore often (ever?) matched, so this would be something new and I don't now what value that would bring.

**Comment by gijzelaerr** [comment]
In my opinion having CASA just depend on the casacore released here is a great win. I've been trying to get CASA compiling, integrated and packaged up for a more modern linux distribution for a while now, but until now this ended up in partial success. One of the biggest barriers is that CASA uses modified existing software as dependencies, for example casacore. That makes it very hard to make CASA installable/packagable together with other radio astronomy libraries that link to the unmodified libraries.

Making CASA depend on the casacore code released here and don't fork and modify it is a great start for modernising the CASA code base. Hopefully some day it makes it possible unravel the big release tarball it is now and get the code building on something more modern than red hat enterprise 6 and let it integrate with the system python.

**Comment by gijzelaerr** [comment]
Just to give a bit more context, because I'm not sure if everybody knows about the things discussed and what was the progress. About 1.5 year ago there where some serious plans and effort spend to make CASA also work on other/newer linux distributions and unravel the big tarball. This was decided between a cooperation effort between SKA SA and NRAO. I've put quite some effort in researching the CASA code base and compiling it on a more modern Linux distribution (Ubuntu 14.04 in this case).

Most of the work is in these two repositories:

https://github.com/radio-astro-debian/casa-code-debian
https://github.com/radio-astro-debian/gcwrap-debian

And there are even some debian packages in the radio astro ubuntu launchpad PPA:

https://launchpad.net/~radio-astro/+archive/ubuntu/main

To properly package the code and gcwrap modules up one of the biggest problems I had until now was the modified casacore. It just becomes impossible to install the resulting packages with other packages that depend on casacore. So please please please pretty please with sugar coating and a dutch stroopwafel on top consider sticking with the released casacore code and/or improve the synchronisation between the NRAO releases for the sake of global radio astronomy software usage pleasure.

**Comment by juliantaylor** [comment]
trying to use the same casacore library from multiple independent software packages is just asking for trouble. Alone trying to keep the abi stable would be very costly if even possible at all.
I don't see the problem of each package shipping their own casacore as long as all try to keep the changes they need minimal and contribute to them back to same core repository as we are currently trying to do.

that we only support old redhats should also not be such a large problem the more time goes on, newer distributions (including redhat7) usually have native support for containers which make the distinction between operating systems even more obsolete than good old `chroot` did. Fwiw. our main development server at ESO is an ubuntu 14.04 box with a bunch of centos containers on it.

**Comment by gijzelaerr** [comment]
I don't fully understand why it would be a trouble. If NRAO requires changes to casacore, these can be implemented, evaluated,peer reviewed and incorporated into a stable release. It sounds like CASA developers want to be able to quickly hack changes into the library and not wait for the casacore developers to evaluate these changes. Now This sounds much more like asking for trouble from your side if you ask me, since it complicates your and our development cycle where code needs to be merged around and re-engineered. Why not just think a bit before implementing a new feature, design and plan it and then implement it in a proper way? We are working on one of the core and most used libraries in radio astronomy here, quality and proper planning is important.

Using containers still doesn't enable to run various tools that depend on the same libraries in the same memory space if they use conflicting libraries. Containers are process separation, but if you want to compose a program with various dependencies they still need to live in the same containers.  I believe containers can be useful here, but more as a workaround than a real solution. I have tried making a CASA container, but it becomes huge and is hard to combine with other software:

https://registry.hub.docker.com/u/radioastro/casapy/

**Comment by juliantaylor** [comment]
I think you are underestimating the effort needed in order to have a stable abi. It is already hard enough for a C library to maintain an abi and still be able to progress. For a C++ library which has not been designed to be abi stable from ground up and is developed by scientific oriented developers this is almost impossible.
Pretty much every code change done in the last few weeks broke it in some way or another. There isn't even a single visibility attribute in casacore.

I don't see the point of even trying to maintain it when it only costs you a few mb of diskspace and ram for each project to ship their own casacore.
Though I am not in any position to make any policy so I'll stay out of this discussion for now.

**Comment by gijzelaerr** [comment]
Sticking to a unmodified released software doesn't introduce ABI instability, this enables stability? Again it is not about saving disk space or ram, it is about composing various software packages that depend on shared libraries.

Indeed this is getting off topic, so lets just hope the policy makers read this and come up with a policy about this.

**Comment by tammojan** [comment]
Coming back on topic: there is an issue with Lofar with the casacore 2.0.1 release. We would like to release 2.0.2 which has the fix. Does anyone have a problem with a casacore 2.0.2 release? Otherwise let's make one on Monday.

**Comment by tammojan** [comment]
Closing this topic, since now 2.0.3 has been released.
