### ISSUE TITLE
Travis build+test time too long

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#142]
The travis job is right at the edge of too long, causing it to abort sometimes. This is unpractical for development. We could trim down the test time by disabling one of the builds (for example, build only clang and not gcc for osx).

This certainly blocks #115.

**Comment by tammojan** [comment]
(We could also ask travis what it would take to increase the test time.)

**Comment by juliantaylor** [comment]
building with -j2 might help a little bit as travis gives us 1.5 cpu cores.

Another option is using their container based setup instead of the VM based one, besides faster startup that does allow using a cache for free. One could  e.g. cache a ccache cache which could massively speed up the builds not touching common headers. Though it implies building without debug symbols as those are huge.
Though I think containers cannot use ppas

can the build be split up into several subcompiles/test? that also allows working around the one-job timelimit.

**Comment by tammojan** [comment]
@gijzelaerr Why aren't we using a container based setup?

**Comment by gijzelaerr** [comment]
because we use packages from the PPA for the ubunu build, which requires root permissions to install.

But since we download the casacore data manually now that only is the custom wcslib back ported to 12.04. 

But maybe it is possible to use a more recent Ubuntu image with a more recent wcslib if we switch to docker.

**Comment by JimNrao** [comment]
Sort of related: is there an easy way to have Travis send e-mail to the 
PR author if build/test fails?

On 6/30/2015 4:27 AM, Gijs Molenaar wrote:
>
> because we use packages from the PPA for the ubunu build, which 
> requires root permissions to install.
>
> But since we download the casacore data manually now that only is the 
> custom wcslib back ported to 12.04.
>
> But maybe it is possible to use a more recent Ubuntu image with a more 
> recent wcslib if we switch to docker.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/142#issuecomment-117117056>.Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtLqSl1KdacaPzDmJKEKOWx8HvlYFks5oYmaigaJpZM4FOSAi.gif
>


-- 
Jim Jacobs

**Comment by tammojan** [comment]
> Sort of related: is there an easy way to have Travis send e-mail to the PR author if build/test fails?

Should be easy (but reading the documentation, it seems it should be enabled by default): http://docs.travis-ci.com/user/notifications/#Email-notifications

**Comment by tammojan** [comment]
If fixing #148 is not too hard, then casacore would run on the default Ubuntu repositories, with wcslib 4.8.3. I assume that would make using containers easier, so I'll have a look at #148.

**Comment by gijzelaerr** [comment]
btw, maybe the paid version of travis supports longer test runs? It is not
cheap though.

2015-07-04 7:32 GMT+02:00 Tammo Jan Dijkema <notifications@github.com>:

> If fixing #148 <https://github.com/casacore/casacore/issues/148> is not
> too hard, then casacore would run on the default Ubuntu repositories, with
> wcslib 4.8.3. I assume that would make using containers easier, so I'll
> have a look at #148 <https://github.com/casacore/casacore/issues/148>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/casacore/issues/142#issuecomment-118463053>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by tammojan** [comment]
Since #146 has now been fixed, in principle we can now use containers for linux builds. I've tried this on the branch [travis-docker](/casacore/casacore/compare/travis-docker). However, this does not yet play nice with the OSX build. Will contact travis support about that.

**Comment by tammojan** [comment]
The linux travis now builds in a container (#185). The OSX build is still too slow. Perhaps we can use `-DMODULE=ms` on OSX to skip building the images module.

**Comment by tammojan** [comment]
Seems to be fine now that we use containers, and now that travis sorted out their OSX issues.

Still, the build time is awfully long, but that's another issue.
