### ISSUE TITLE
Support negative indices in Slicer

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#343]
It would be nice if it is possible to specify negative indices in the Slicer start and end value. Just as in Python they mean counting from the end.

**Comment by alxames** [comment]
Should we throw/raise not only if idx >= size, but also if idx < -size, just like in python?

**Comment by gervandiepen** [comment]
It does throw if idx<-size, because it first adds the size and thereafter checks the result. Or do you prefer an explicit message (which Python does not give)?

**Comment by alxames** [comment]
Yes, afterwards away from my terminal I realized the code might take that approach. I then realized that in Python you can do that, but in C/C++ there is an overflow issue when index is very large, e.g. INT_MAX. Not sure if this is severe enough to warrant an improvement, since the rest of casacore may not care for this either (and I now see we got that subtly wrong in LOFAR DAL too).

No preference for an explicit message here.
If you change the message at all, adding the offending index would be nice, but the concat is a little tricky with const char *. I'm a little doubtful about how this is done in LOFAR software. Perhaps boost has a better way to do it, but no problem as-is.
