### ISSUE TITLE
Create a function to clone a table column

### ISSUE THREAD

**Issue by gervandiepen** [casacore/casacore#354]
It is very useful if a column like DATA can be cloned to, say, CORRECTED_DATA using the same column description and data manager properties. The column should be filled from an existing column, either by copying its data or by creating an array with the same shape filled with a constant value.

**Comment by gervandiepen** [comment]
@JimNrao 
How far are you with testing this functionality in CASA?

**Comment by JimNrao** [comment]
I installed it and ran the test case that I was trying to fix but the 
results seemed different but wrong.  I'm trying to debug/characterize 
them a bit.

On 04/07/2016 07:46 AM, Ger van Diepen wrote:
>
> @JimNrao <https://github.com/JimNrao>
> How far are you with testing this functionality in CASA?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/354#issuecomment-206912406>Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtPPmGXlRXlVMLZwgnJX82-INYu9Qks5p1QrLgaJpZM4H4C84.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301

**Comment by JimNrao** [comment]
Looks like the cloning operation loses the existing hypercube shapes, 
probably because the new column has no hypercubes at the time of the 
cloning.  Only the default tile shape goes into the cloned column.  Is 
there a way to forcibly create the necessary hypercubes but keep them empty?

On the plus side the cloned column doesn't cause the utilities to report 
it as having a type mismatch.

On 04/07/2016 07:46 AM, Ger van Diepen wrote:
>
> @JimNrao <https://github.com/JimNrao>
> How far are you with testing this functionality in CASA?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/casacore/casacore/issues/354#issuecomment-206912406>Web 
> Bug from 
> https://github.com/notifications/beacon/AGPGtPPmGXlRXlVMLZwgnJX82-INYu9Qks5p1QrLgaJpZM4H4C84.gif
>

-- 
Jim Jacobs

phone: 835-7235
office: 301
