### ISSUE TITLE
ABI changes, version numbers and SONAME

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#433]
casacore is about to be packaged up and distributed in Debian. This made me realise that we need to make sure we manage our SO versions correctly.

https://en.wikipedia.org/wiki/Soname

idea now is that we would only allow ABI changes in major releases, but that may not be feasible.

This issue is for now a reminder to check if this is working correctly.

**Comment by juliantaylor** [comment]
speaking with my seasoned debian maintainer and ubuntu developer hat on, I think packaging casacore in debian is a really bad idea. The result is just going to be an outdated library in the repository syphoning QA time that would be better spent elsewhere.

Concerning casacore, I obviously cannot make any decisions on policy, but a large fraction of the PRs merged in the last few month broke the ABI, so for packaging you can probably expect a soversion bump on each release and it will likely have to be you to actually do the bumping because nobody else really cares.

**Comment by gijzelaerr** [comment]
Hm, you may be right, but I'm not initiating or controlling the packaging in any way. My interest is to package up casacore properly, but not necessarily get it into Debian. Still this is open source software, so if people want to take the effort in getting it into Debian and maintaining it there I see no objections.

Still I think it is a good idea to manage our soversion properly. If that means increasing it for every ABI break than that is something that has to happen.

**Comment by olebole** [comment]
@juliantaylor To put my Debian-Hat on (I am the sponsor of the casacore Debian package): casacore is one of the wider used packages in astronomy, and a number of binary packages depend on it -- see @gijzelaerr's [kernsuite](https://github.com/kernsuite-debian) repository.
Having casacore in Debian provides easy and consistent access for astronomers to that software. And there is nothing in the [Debian Policy](https://www.debian.org/doc/debian-policy/) that would prevent us.
I would not fear SONAME changes; transitions are a well-established and (as long as the API is compatible) automated procedure in Debian. As a plus, it gives 

- regular [CI tests](https://ci.debian.net/) with every change of the runtime environment (on x86_64 for Debian, on many CPU types on Ubuntu) if enabled in the package,
- [build tests](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/casacore.html) (via https://reproducible-builds.org/) on many architectures,
- code reviews, help on bug fixing by Debian people etc.

It also puts some pressure on casacore to follow good practices, like the ABI/SONAME discussed here in this issue, which is finally good for casacore as well. So, finally, all will benefit: users (who get casacore and its dependent packages out of the box), developers (who will get a great feedback), and the Debian/Ubuntu/Mint distributions (which will gain popularity).

As always, I would recommend you to discuss these topics on the [Debian Astro Mailing list](https://lists.debian.org/debian-astro/), which is specifically made for these topics.

**Comment by gijzelaerr** [comment]
Maybe I also don't understand the full problem here. We don't do a crazy amount of releases. What is the big problem to update the SO number if a ABI breaks for a release? You keep saying 'nobody cares', but I think that means CASA people don't care. Maybe you don't realise, but there are a indeed lot more people using casacore outside of CASA.

**Comment by tammojan** [comment]
Currently the CASA release does different things to the SONAME than if you build it yourself. See 
https://github.com/casacore/casacore/blob/master/CMakeLists.txt#L435 (the CASA version) and https://github.com/casacore/casacore/blob/master/CMakeLists.txt#L442 (the non-CASA version). So I don't think this affects the CASA group too much.

For the non CASA users, having a proper release and packaging is useful. There are many (order 10) programs which use Casacore, and one probably wants them all to use the same version of casacore (so releasing is useful). And not everyone wants to build casacore from source and manage versions (so packaging is useful).

**Comment by olebole** [comment]
@tammojan I just checked the SONAME for the CASA case. It is mainly created by a perl script, introduced in 750af188, which is horrible (at least for a release): it just uses the current time for the soversion.
Can't we just take a single number, and increase that with every ABI incompatible version here? Maybe start with `${PROJECT_VERSION_MAJOR}+1` since the current release already has `${PROJECT_VERSION_MAJOR}` (== 2).
Releases seem to be quite rare (~2 per year), so this should not be a big problem, even when every release in incompatible.

**Comment by alxames** [comment]
> What is the big problem to update the SO number if a ABI breaks for a release?

None really, though I prefer a slightly different guideline. I see argued and/or I find that:
* searching/tracking 6 months of commits for ABI breakage is a waste of time: just assume it broke and update SO.
* get ABI analysis over 6 months wrong once and someone else spends more time debugging than everyone else saved on rebuilding.
* having SONAME == filename is really clear for tool developers and sysadmins/users. You can easily see when to rebuild tools and it becomes a lot easier to build or even reuse a casacore plugin usable from CASA (e.g. LOFAR raw .MS storage mgr).

So don't update the SO number just on ABI breaks, but on every ~6 month release.
Small ABI compatible fixes of a release crippling bug can still be turned into a sub/patch release.

So we could have SONAME libcasa_xxx.so.x.y instead of now SONAME libcasa_xxx.so.x and use the .z part in version numbers only (i.e. git tags and version #defines). Note that the .z should not end up in the filename (unlike now), as a sub/patch release must be installed by replacing the buggy lib. (And let's drop installing symlinks.)

I have no objections to part of olebole's comment to bump PROJECT_VERSION_MAJOR (i.e. x) instead of .y (now). I'd presume we then would use .y as ABI compatible fix nr and drop .z. Then SONAME is libcasa_xxx.so.x (as-is), but we need to install filenames as libcasa_xxx.so.x (and again, let's drop the symlinks).
However, with only x.y we can no longer notify users of significant API changes that may require porting effort instead of just a rebuild. (Maybe I misunderstood olebole.)

If CASA could drop their custom SONAME scheme (and not introduce ABI incompat build flags), anyone can instantly recognize any compat CASA shipped casacore and link to it where useful. 
I expect their concern to be that with a non-unique name to link to, it's too easy to accidentally have CASA libs link to other casacore or system libs. But that's better solved using RPATH correctly. If distro pkgs don't like that, we can elide it like AOFlagger and WSClean do, or add a switch. Ideally, CASA, casacore and python-casacore use $ORIGIN in RPATH on platforms where supported, such that users can continue to extract an archive with CASA binaries and relocate it to the preferred directory.

(Earlier SONAME discussion in #192)

**Comment by olebole** [comment]
> *    searching/tracking 6 months of commits for ABI breakage is a waste of time: just assume it broke and update SO.
> *    get ABI analysis over 6 months wrong once and someone else spends more time debugging than everyone else saved on rebuilding.

While I am fine with that, I wonder why you need to search here at all? If someone broke the ABI he should know and document this.
BTW, there is a [collection of tools that check ABI compliance](https://github.com/lvc) available, even in [Debian](https://packages.debian.org/sid/abi-monitor). In the past, there also was a [web page](http://upstream.rosalinux.ru/) for that, but they don't update it anymore. However, the tools is great for the check.

> *    having SONAME == filename is really clear for tool developers and sysadmins/users. You can easily see when to rebuild tools and it becomes a lot easier to build or even reuse a casacore plugin usable from CASA (e.g. LOFAR raw .MS storage mgr).

The easiest for sysadmins and users would be to do it standards-wise as long as there is not reason why casacore should be different from f.e. wcslib or CPL. It is always ugly and a source of errors if just one package does the things differently from others.

> So don't update the SO number just on ABI breaks, but on every ~6 month release.
> Small ABI compatible fixes of a release crippling bug can still be turned into a sub/patch release.

As far as I understand @juliantaylor, the ABI is usally broken anyway after 6 months, right? I would have no problems with that proposal.

> However, with only x.y we can no longer notify users of significant API changes that may require porting effort instead of just a rebuild.

You could add a section "API changes" in `CHANGES.md`. This would have the fortunate plus that you can give migration hints which would help users (and packager like me) to bring the system up to date.
And, checking the changelog is always a good idea when updating.

> I expect their [*CASA*] concern to be that with a non-unique name to link to, it's too easy to accidentally have CASA libs link to other casacore or system libs.

I didn't completely follow this: *Is* CASA now compatible to the according CASACORE libs or not? If yes, there is no danger to link them (as long as the ABI is supported, but that is resolved with this issue). If they are anyway not compatible at all -- wouldn't it be better to have different names then? The casacore libs could then be named `libcasacore-XXX` instead of `libcasa-XXX`. Could you give a link on where the current (and future) relation between casa and casacore is documented?

**Comment by gijzelaerr** [comment]
As far as I know, we do this properly now.
