### ISSUE TITLE
excessive cache flushing with Lattices

### ISSUE THREAD

**Issue by juliantaylor** [casacore/casacore#453]
In casa we have an issue that we want to update a Lattice in an order which does match too well with the tileshape.
For this purpose the backing PaggedArray has the bucketcache which is supposed to collect partial tile writes and write them out when they are fuller.
Unfortunately the Lattice infrastructure seems to flush the caches everywhere making the cache moot.

E.g. consider this code:

```c++
#include <casacore/lattices/Lattices/SubLattice.h>
#include <casacore/lattices/Lattices/PagedArray.h>
#include <casacore/casa/Arrays/AxesSpecifier.h>
#include <casacore/casa/Arrays/Vector.h>
#include <casacore/casa/Arrays/IPosition.h>
#include <casacore/casa/Inputs/Input.h>

#include <casacore/casa/namespace.h>

int main (int argc, const char* argv[])
{
    int nx = 400, ny = 400;
    PagedArray<Float> pa(IPosition(3,nx, ny, 100), "tLattice_tmp.pa");
    PagedArray<Float> pb(IPosition(3, nx, ny, 1), "input.pa");
    pa.set(1.5);
    pb.set(2.5);
    for (int i = 0; i < 100; i++) {
        Slicer slicer(IPosition(3, 0, 0, i), IPosition(3, nx, ny, 1));
        SubLattice<Float> sl(pa, slicer, True);
        int r = sl.advisedMaxPixels();
        cout << sl.shape() << " " << pb.shape() << " " << sl.advisedMaxPixels() << " " << sl.niceCursorShape() << endl;
        sl.copyData(pb);
    }
    return 0;
}
```

here it correcty chooses 64 buckets as cachesize so it should just writes 62mb of data one full tile at a time. But copyData creates a dummy temporary LatticeIterator for some reason. The destruction of this iterator triggers a cache flush and it actually writes out 10 times more data than necessary (the tileshape is 50,50,10).
This goes against the documentation saying iterators should be short lived, when the flush the cache on destruction the must be long lived.

Similarly the LatticeExpr also flushes the cache on destruction which is a major problem for these types of iterations that do not match the tile ordering.

Is there something I am missing or is the cache just actively harmful in combination with Lattices?

**Comment by juliantaylor** [comment]
Assuming I made no mistakes, how to best fix this?

My first idea would be to add a `setFlushOnDelete` function and member to the `LatticeBase` and have the `PagedArray` check this to decide whether it should flush.
The `LatticeIterator`, `SubLattice` and `LatticeExpr` will always set this as they are all subclasses of another lattice with shorter life. Any other classes that should be considered?

Another option might be to add a reference count to `PagedArray` and only flush when it reaches zero, though that might also entail thread safety problems.

**Comment by gervandiepen** [comment]
The cache should not be useless in combination with lattices.
Next week I'll try to take a look at it while I'm at an SKA SDP meeting.
Thereafter I'll be 5 weeks away on vacation.

**Comment by juliantaylor** [comment]
hm isn't it enough to just remove the flush from the PagedArray destructor?
The table reference its holds is a reference to the real table which will flush itself on its real destruction.

**Comment by gervandiepen** [comment]
Lattices without modified data should not do any flushing; it's only that
it checks for all tiles in the cache if they are dirty.
I assume you mean that real disk-IO is being done.
Removing the flush could be done if the PagedArray is not writable,
otherwise it is necessary.

**Comment by juliantaylor** [comment]
they are all dirty, but they are flushed when they are only partially modified, in the example when 50x50,1 of the 50,50,10 pixels are changed every time a Lattice connected object like an iterator or expression is destroyed.
The problem is not really a bug in the code but an inheritance/composition problem.

When the array is not writeable the cache is not needed all so this is not an option.
Why can the flush not be removed? doing so fails a test but can you explain why this is a problem?

**Comment by juliantaylor** [comment]
Fwiw my first idea with the `setFlushOnDelete(off)` does work and I have the code for it, but it feels too much like a workaround for a design issue to me for post right now.

**Comment by gervandiepen** [comment]
I don't have to time to take a detailed look, but will do so next week.
I took a brief look and I assume you mean the use of itsTable.flush in the
PagedArray dtor. I must confess I do not really know why that was done.
Is the problem that, say 10 PagedArray objects reference the same table and
each of them changes 10% of each tile? Than I can indeed see that each tile
gets written 10 times due to that itsTable.flush. I'll try to remember why
it was done that way. Removing the flush should in principle be harmless
because the table flushes itself at the end.

**Comment by juliantaylor** [comment]
Yes that is the problem and the user cannot do anything about it as the PagedArray references get created and destroyed inside the `LatticeIterator` object inside `copyData`. The same issue applies to `LatticeExpression` indirectly via the `SubLattice` or `SubImage`.

Removing the flush also seems to break some casa regressions, but I don't understand why yet.

**Comment by gervandiepen** [comment]
I agree it was an oversight that PagedArray would be used that way and it is bad.

As a test I've removed the flush from PagedArray and noticed that only tImageUtilities failed, which could easily be fixed by adding an explicit flush after line 68.
If removing the flush works fine with the CASA tests, I propose to do so.
Note you can use
     img.showCacheStatistics(cout)
to show how the tiled IO behaves.

**Comment by juliantaylor** [comment]
the issue I fear is that that flush as enabled adding loads of bugs into the higher level code. E.g. due to it you don't have delete your objects or close your files when you open them again later. Removing the flush will make these leaks cause inconsistent data on disk. Some casa tests are failing when you remove the flush. I'll have a look if its reasonable to fix them.
The flush in tImageUtilities would just be a workaround for the issue again, the actual problem is elsewhere, the code structure there does not imply the need for a flush.

**Comment by juliantaylor** [comment]
tImageUtilities actually fails in line 77, I though its an issue in ImageToFITS, so a flush there would be correct.
But this is the issue I fear is going to be everywhere in the ecosystem and hard to track down all instances of

**Comment by gervandiepen** [comment]
It should not invoke bugs as such, because the underlying Table destructor
will always do the flush. If data in CASA tasks are not flushed, it is a
CASA bug (a leaking Table object), not a casacore bug.
However, a problem (which appeared in tImageUtilities) is that the Table
flush might be done too late for certain operations (e.g. if the disk file
is used before the flush is done), but that should hardly ever be the case.
A solution might be that the PagedArray destructor is only doing the flush
when the reference count gets zero. That is easy to do.

**Comment by juliantaylor** [comment]
it is a sort of bug, but one that is everywhere because it is allowed.
Consider:

   t = iatool()
   t.fromshape("img", [20, 20])
   t.calcmask("img == 0")

the calcmask opens the table from the filename, but it hasn't been flushed yet so it fails. Also casacore has a table cache so tables might not even be flushed when you expect them to.
The fix would be to close and open the iatool, but it has to be done in a lot of places.
A option to keep this working might be to check for open tables whenever a disk table is opened. If a table referencing that file is already in the cache, flush it.

**Comment by gervandiepen** [comment]
The table system already checks for open tables and doesn't open again if
already open (but I guess you know that). Flushing when opening it again
seems bad to me, because you open the same table 10x, so it would also mean
the data gets flushed 10x.

Does calcmask open it as a table or does it try to find the file to see
what type of file it is? The latter was the problem in tImageUtilities
(because it checks if the image is FITS, Miriad, etc.), and that is
probably also the problem for calcmask. If opened as a table, it should
have found it in the open table cache.
So a possible solution is first trying to open it as a table and if that
fails, check for FITS, etc.

I do not fully understand your remark about the table cache. You mean the
open table cache? Indeed the automatic flush of a table (usually a
PlainTable) is only done when the last reference disappears. When would you
expect it to be flushed? When a Table object gets destructed? In that case
you might also have the 10x flush problem.

**Comment by juliantaylor** [comment]
it goes over the TableExprParse.cc stuff.
The issue is that this uses Table::IsReadable which tries to read `table.dat`. But that file has not been written yet.

When you open a table once for read and once for write is it still only one reference the same table object?
If it is guaranteed that a specific table on disk always is one single global table object, maybe one can get away with not flushing if we can figure out a way to make the functions looking at the disk like `IsReadable` work.

**Comment by gervandiepen** [comment]
I had a good idea. Table::isReadable can first look in the table cache. If
so, it knows it is a table, thus returns True.
Here you have the diff. Could you try it to see if it works (in combination
with the removal of flush in PagedArray).

--- a/tables/Tables/Table.cc
+++ b/tables/Tables/Table.cc
@@ -868,6 +868,11 @@ Table Table::operator! () const
 Bool Table::isReadable (const String& tableName, Bool throwIf)
 {
     String tabName = Path(tableName).absoluteName();
+    // First see if it is in the table cache. By doing so a new table
+    // does not need to exist on disk yet.
+    if (PlainTable::tableCache()(tabName)) {
+      return True;
+    }
     //# Check if the table directory exists.
     File dir(tabName);
     if (!dir.exists()) {

**Comment by juliantaylor** [comment]
next the ImageOpener uses TableInfo to figure out the type of table, I guess that needs changing to use the table from the cache too

**Comment by juliantaylor** [comment]
good that fixes this particular testcase, lets see tomorrow how the full casa suite fares
