### ISSUE TITLE
cmake doesn't handle XYZ_INCLUDE_DIR properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [casacore/casacore#49]
```
There seem to be inconsistencies in handling explicitly given include dirs 
and/or handling of ones coming from XYZ_ROOT_DIR.

CFITSIO_ROOT_DIR=blah seems to translate into CFITSIO_INCLUDE_DIR
WCSLIB_ROOT_DIR ditto

FFTW3_ROOT_DIR doesn't show in the -I flags
FFTW3_INCLUDE_DIR doesn't show in the -I flags
FFTW3_INCLUDE_DIRS works.

Also there seems to be no way to tell the cmake's FindBLAS/LAPACK to use a 
custom directory e.g. BLAS_ROOT_DIR. Only explicit absolute path BLAS_LIBRARIES 
work.

I also fixed the CmakeInstructions where the wrong options were listed.

```

Original issue reported on code.google.com by `Malte.Marquarding` on 26 Mar 2012 at 5:40

**Comment by tammojan** [comment]
I'm not sure this is a valid bug. `CFITSIO_ROOT_DIR` is used to find cfitsio, and usually the include is in `CFITSIO_ROOT_DIR/include`, which gets written to `CFITSIO_INCLUDE_DIR`. Same for wcslib. 

`FFTW3_ROOT_DIR` should not show in include flags, since it is not an include directory. `FFTW3_INCLUDE_DIR` is set by FindFFTW3 to be the same as `FFTW3_INCLUDE_DIRS`, which is added to the include flags.

About FindBLAS: we use the default CMake module to find blas. If it doesn't work properly, that should be fixed in cmake.
