### ISSUE TITLE
Link Error On Sierra+Gcc6

### ISSUE THREAD

**Issue by cnwangfeng** [casacore/casacore#589]
Hi, I met a error when compile casacore on Macbook Pro with Sierra. 
```
[100%] Linking CXX shared module _tConvert.so
Undefined symbols for architecture x86_64:
  "boost::python::objects::function_object(boost::python::objects::py_function const&, std::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&)", referenced from:
      casa::python::testConvert()     in tConvert.cc.o
  "boost::python::objects::register_dynamic_id_aux(boost::python::type_info, std::pair<void*, boost::python::type_info> (*)(void*))", referenced from:
      casa::python::testConvert()     in tConvert.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [python/Converters/test/_tConvert.so] Error 1
make[1]: *** [python/Converters/test/CMakeFiles/tConvert.dir/all] Error 2
make: *** [all] Error 2
WF-MacBook-Pro:casacore-build wangfeng$
```
GCC6 was installed by Homebrew. Python's version is 2.7.

**Comment by tammojan** [comment]
Did you install boost-python also with homebrew? And are you building casacore with C++11 enabled? If you don't know, look in `CMakeCache.txt` in the build directory for a line with `CXX11`.
Just googling shows [this](http://stackoverflow.com/questions/20134223/building-a-boost-python-application-on-macos-10-9-mavericks/) which seems to point to some C++11 incompatibility.

**Comment by cnwangfeng** [comment]
Hi, Tammojan. Thanks for you comments. I have tried installing boost-python with source code and non-source code by Homebrew. The results are the same. I checked the CMakeCache.txt. Current CXX11 is On. 

I can compile casacore with Apple LLVM (Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0) successfully. However, there are no GFORTRAN in Apple LLVM.

Any comments are appreciated.

**Comment by cnwangfeng** [comment]
I modified CMakeCache and changed C++11 from On to OFF. It's pity the final file cannot be linked either.

**Comment by tammojan** [comment]
I'm using casacore on sierra myself, with the following setup:
* LLVM: Apple LLVM version 8.1.0 (clang-802.0.42)
* gfortran: gfortran-6 (as installed with Homebrew)
* boost: as installed with Homebrew
* CXX11 = ON

So it is not necessary to use the same compiler for gfortran as for c++. The problem comes from `boost-python`, so it would be interesting to see with which compiler that was compiled. It will probably help if `boost-python` was built with the same compiler as the one you use for casacore. I think Homebrew uses the system compiler by default, so using the system compiler (LLVM) might be the best solution.

I'm not sure what you intend to use casacore for. If you do not need python-casacore, you could build with `-DBUILD_PYTHON=Off` which would avoid linking to boost-python.

**Comment by cnwangfeng** [comment]
In current project, I will compile Sage-cal and test for SKA-SDP. Of course it's no error under Linux. However, I also want to compile casacore on my Mac laptop. I agree that the problem comes from boost-python. 

Of course I can avoid the problem with no compiling with python-casacore. But you know, I do hope that casacore would be perfect. ;-)

**Comment by JasonRuonanWang** [comment]
@cnwangfeng 

I used to have a lot of problems when cross-linking libraries that are compiled with different compilers (Clang and GCC). I am almost sure that this is because the home-brew version of boost is compiled using Clang (LLVM) and thus is not compatible with GCC when you link it from casacore. I can have a try for you to compile boost using GCC as well and let you know if that works.

**Comment by JasonRuonanWang** [comment]
@cnwangfeng 

Yeah, it worked for me, although there are heaps of warnings. I had the same problem as you posted when linking to home-brew boost. But as soon as I switch to the GCC compiled boost it worked for me.

Below is how I compile boost and casacore:

Boost:
Mac-Pro:boost_1_64_0 jason$ CC=gcc CXX=g++ ./bootstrap.sh --prefix=$libpath/boost --with-python=python
Mac-Pro:boost_1_64_0 jason$ ./b2 install -j32

casacore:
Mac-Pro:build jason$ CC=gcc CXX=g++ cmake .. -DWCSLIB_ROOT_DIR=$libpath/wcslib -DBoost_INCLUDE_DIR=$libpath/boost/include
Mac-Pro:build jason$ make -j32

**Comment by cnwangfeng** [comment]
Thanks. Runnan. I will have a try. What's the GCC version of your Mac?  I have tried the approach of tammojan by using Clang to compile Casacore and only adding Gfortran-6. However, the error occurred when I compile sage-cal with GCC.

**Comment by tammojan** [comment]
I don't think sagecal needs the Python bits of casacore? Which error occured when compiling sagecal with GCC?

**Comment by cnwangfeng** [comment]
Yes.  Sagecal doesn't need python indeed. But the error of "ld: symbol(s) not found for architecture x86_64" will display when link casacore libraries.

**Comment by tammojan** [comment]
For which symbols? Are they boost-related?

**Comment by cnwangfeng** [comment]
No. Not boost-related. 

x86_64-apple-darwin16.5.0-c++-6 -O3 -Wall -g   -I. -I./lib -I/usr/local/include -I/usr/local/include/casacore/ -I/usr/local/opt/openblas/include -I/usr/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -L/usr/local/opt/openblas/lib/ -L/usr/local/lib/  -L/usr/local/opt/gcc/lib/gcc/6/ -L./lib  -o sagecal  main.o data.o -lm -lsagecal  -lopenblas -lgfortran -lpthread -lcasa_casa -lcasa_tables -lcasa_measures -lcasa_ms -lcfitsio  -lglib-2.0
Undefined symbols for architecture x86_64:
  "casa::ArrayColumn<std::complex<float> >::put(unsigned int, casa::Array<std::complex<float> > const&)", referenced from:
      Data::writeData(casa::Table, Data::IOData)   in data.o
      Data::writeDataList(std::vector<casa::MSIter*, std::allocator<casa::MSIter*> >, Data::IOData) in data.o

**Comment by JasonRuonanWang** [comment]
@cnwangfeng I was using GCC 6.3. I don't think it has too much to do with the GCC version. Base on my experience casacore has been pretty robust since 2.0 and should work with any mainstream compiler. But you need to be extremely careful when sorting out the paths. CMake is sometimes weird. Even if you think you are linking with the boost version that you compiled yourself, it might be using the home-brew boost underneath. Also, when you compile boost yourself you might be accidentally using Clang (LLVM) without awareness. 

Sometimes even if you are using GCC, the header or library files that come with Clang might have higher priority in your environment variables, so GCC is picking up these files from the Clang (LLVM) distribution. I had a lot of problems because of this when compiling C++11 code. 

The safest way is:

1. uninstall boost from home-brew.
2. manually delete any boost library and header files if there is.
3. Make sure GCC/bin, GCC/include, GCC/lib or GCC/lib64 is in your PATH, CPATH, LIBRARY_PATH and DYLD_LIBRARY_PATH respectively. Also, this is very important: make sure they are in front of /usr/bin, /usr/include, /usr/lib etc.
4. Run "which gcc" and see if the default compiler is GCC 6.3.
5. Always put "CC=/absolute/path/to/your/gcc", and "CXX=/absolute/path/to/your/g++" in front of your cmake. So it's going to be like:
CC=/absolute/path/to/your/gcc CXX=/absolute/path/to/your/g++ cmake ..

**Comment by JasonRuonanWang** [comment]
Also don't forget delete all casacore files and untar form the tar ball every time you try different things...

**Comment by JasonRuonanWang** [comment]
x86_64-apple-darwin16.5.0-c++-6 -O3 -Wall -g   -I. -I./lib -I/usr/local/include -I/usr/local/include/casacore/ -I/usr/local/opt/openblas/include -I/usr/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -L/usr/local/opt/openblas/lib/ -L/usr/local/lib/  -L/usr/local/opt/gcc/lib/gcc/6/ -L./lib  -o sagecal  main.o data.o -lm -lsagecal  -lopenblas -lgfortran -lpthread -lcasa_casa -lcasa_tables -lcasa_measures -lcasa_ms -lcfitsio  -lglib-2.0
Undefined symbols for architecture x86_64:
  "casa::ArrayColumn<std::complex<float> >::put(unsigned int, casa::Array<std::complex<float> > const&)", referenced from:
      Data::writeData(casa::Table, Data::IOData)   in data.o
      Data::writeDataList(std::vector<casa::MSIter*, std::allocator<casa::MSIter*> >, Data::IOData) in data.o


@cnwangfeng This problem seems to me also very likely because of the mix use of different compilers.  I am pretty familiar with the CTDS storage manager part of casacore. It's been very mature and there is no way that functions in that part can go wrong, especially if you are using a stable release of casacore. 

Using GCC on a Mac has always been very tricky. I have been struggling a lot. Most of this kind of problems I have ever run into are because of accidental mix use of Clang and GCC without awareness. Especially for C++ 11 code, my suspicion is that Clang and GCC use different name mangling methods. So they don't recognize each other's function symbols. Try making sure only one compiler is used across all steps, and I am pretty sure you won't see the error any more.

**Comment by cnwangfeng** [comment]
Yes. Jason. I do agree with you that the mix use of two compilers is the key point of the error. I knew. 👍 I do hope you can find a good way to solve it easily. 

If you also use GCC 6, you can find a series of executive files such as x86_64-apple-darwin16.5.0-c++, x86_64-apple-darwin16.5.0-gcc, and etc. I also tried these files and guess these compilers would produce the codes for architecture x86_64. But the results is frustrating.

**Comment by tammojan** [comment]
So we found out in #596 that this is due to mixing `libc++` with `libstdc++`. MacOS links everything to `libc++`. If your `boost-python` was linked to `libstdc++`, this error will show up. See https://github.com/casacore/casacore/issues/596#issuecomment-303708592
