### ISSUE TITLE
Install issues on Mac OS X

### ISSUE THREAD

**Issue by keflavich** [casacore/casacore#596]
I'm trying to compile casacore on mac OS X by linking against conda-installed libraries.  This may not be entirely sane, but I wanted to post my efforts here and ask if there's anything critical I've missed.

My cmake command involved a lot of flags:

    PATH=~/anaconda/envs/astropy35/bin/:~/anaconda/envs/astropy27/bin/:$PATH cmake .. -DUSE_FFTW3=ON -DBUILD_PYTHON3=on -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON -DPYTHON3_LIBRARY=/Users/adam/anaconda/envs/astropy35/lib/python3.5/config-3.5m/libpython3.5m.a -DPYTHON3_INCLUDE_DIR=/Users/adam/anaconda/envs/astropy35/include/python3.5m/ -DBOOST_ROOT=/Users/adam/anaconda/envs/astropy35/

and looked [mostly successful](https://gist.github.com/keflavich/30f8ec3490618ecb0dcb0625660bf008) up to the [end](https://gist.github.com/keflavich/30f8ec3490618ecb0dcb0625660bf008#file-casacore_make-txt-L4094), when it failed.  The error started around [this line](https://gist.github.com/keflavich/30f8ec3490618ecb0dcb0625660bf008#file-casacore_make-txt-L3408).

My cmake command revealed that I'm [missing SOFA libraries](https://gist.github.com/keflavich/30f8ec3490618ecb0dcb0625660bf008#file-casacore_make-txt-L44) and [CASA data](https://gist.github.com/keflavich/30f8ec3490618ecb0dcb0625660bf008#file-casacore_make-txt-L74), but I don't think either of these things should affect compilation as above.

Any help would be appreciated.

**Comment by tammojan** [comment]
The problem is with boost-python, which is somewhat involved to get installed on mac systems. The boost-python library should be compiled against the appropriate python libraries, i.e. the python libraries belonging to the version of python that is used.

Unfortunately CMake's FindBoost doesn't report the path of boost it found, but I assume it's the one in `/Users/adam/anaconda/envs/astropy27/bin/python2`. Could you check against which python libraries your boost-python was compiled? You could use `otool -L libboost_python.dylib` or `strings libboost_python.a | grep 2.7` if a static library was built along with the shared libraries.

For what it's worth: my own installation uses a homebrew version boost, compiled against the system python 2.7. As soon as I have another python interpreter in my path, I run into issues with `tConvert` (and the python conversion tools will stop working). I actually ran into this today myself.

**Comment by keflavich** [comment]
OK, I'll investigate, but a quick question first - is it possible to build both a py2 and a py3 version simultaneously, as I have tried above?  Would FindBoost always pick the py2 or py3 version independent of which version is being used?  Or is it clever enough to look for `libboost_python3.dylib`/`libboost_python2.dylib`?

**Comment by keflavich** [comment]
`otool -L`  gives:
```
cyg ~/repos/casacore/build master$ otool -L /Users/adam/anaconda/envs/astropy35/lib/libboost_python.dylib
/Users/adam/anaconda/envs/astropy35/lib/libboost_python.dylib:
	@rpath/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.0.0)
cyg ~/repos/casacore/build master$ otool -L /Users/adam/anaconda/envs/astropy35/lib/libboost_python3.dylib
/Users/adam/anaconda/envs/astropy35/lib/libboost_python3.dylib:
	@rpath/libboost_python3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.0.0)
```
which tells me nothing....

but the blank return here:
```
cyg ~/repos/casacore/build master$ strings /Users/adam/anaconda/envs/astropy35/lib/libboost_python.a | grep 2.7
cyg ~/repos/casacore/build master$
```
points back to my question: looks like this `libboost` is for python3 only?

**Comment by tammojan** [comment]
It should be clever enough to find both python2 and python3; the confusion only starts when you have several python2's or several python3's.

**Comment by keflavich** [comment]
OK, it looks like the problem is then that I need two different `BOOST_ROOT`s, one for py2 and one for py3.  I used:
```
-DBOOST_ROOT=/Users/adam/anaconda/envs/astropy35/
```
which is for python3.  Is it possible to specify multiple boost roots?  I could try, but compiling took ~30m last time, so I figure it's best to ask.

**Comment by keflavich** [comment]
(also I do have several py2s/py3s, which is why I'm trying to be as explicit as possible about library & executable paths)

**Comment by tammojan** [comment]
Perhaps start with only python2 and then build up the configuration. 
To make testing a bit quicker, you could add `-DMODULE=tables` to CMake to specify a minimal installation. Also, use `make -j3` to build with three cores (assuming you have a multicore system).

**Comment by keflavich** [comment]
To clean the directory, should I just `rm -r build/` and start over?

**Comment by tammojan** [comment]
Yes.

**Comment by keflavich** [comment]
I tried it, and the build failed here:
```
[ 77%] Linking CXX shared library libcasa_tables.dylib
[ 77%] Built target casa_tables
make: *** [all] Error 2
```
Is that intentional, since I cmake'd with `DMODULE=tables`?
```
cyg ~/repos/casacore/build master$ PATH=~/anaconda/envs/astropy27/bin/:$PATH cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON -DBOOST_ROOT=/Users/adam/anaconda/envs/astropy27/ -DMODULE=tables
```

**Comment by tammojan** [comment]
The output is now a bit confusing (three threads are spitting out output). Please type `make` (without the `-j`) once more to see the actual cause of the failure (I hope it's still python related).

**Comment by keflavich** [comment]
Right.
```
Undefined symbols for architecture x86_64:
  "boost::python::objects::function_object(boost::python::objects::py_function const&, std::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&)", referenced from:
      casa::python::testConvert()     in tConvert.cc.o
  "boost::python::objects::register_dynamic_id_aux(boost::python::type_info, std::pair<void*, boost::python::type_info> (*)(void*))", referenced from:
      casa::python::testConvert()     in tConvert.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [python/Converters/test/_tConvert.so] Error 1
make[1]: *** [python/Converters/test/CMakeFiles/tConvert.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tammojan** [comment]
Could you check `CMakeCache.txt` for `Boost_PYTHON_LIBRARY_RELEASE`, `PYTHON2_EXECUTABLE`, `PYTHON2_LIBRARY`, and most importantly `tConvert_LIB_DEPENDS`?

**Comment by keflavich** [comment]
```
Boost_PYTHON_LIBRARY_RELEASE:FILEPATH=/Users/adam/anaconda/envs/astropy27/lib/libboost_python.dylib
PYTHON2_EXECUTABLE:FILEPATH=/Users/adam/anaconda/envs/astropy27/bin/python2
PYTHON2_LIBRARY:PATH=/usr/lib/libpython2.7.dylib
tConvert_LIB_DEPENDS:STATIC=general;casa_python;general;/Users/adam/anaconda/envs/astropy27/lib/libboost_python.dylib;general;/usr/lib/libpython2.7.dylib;
```
The python library path is a problem.

**Comment by tammojan** [comment]
Great, gotcha. Could you edit that path in `CMakeCache.txt` and run `make` again?

Looking at `FindPythonLibs.cmake` (from CMake), I think you can specify `-DPYTHON2_EXECUTABLE=/Users/adam/anaconda/envs/astropy27/bin/python2` to the CMake call to get it to find the right libraries; that's the next thing to check.

**Comment by keflavich** [comment]
I've tried again with a new `cmake` command:
```
PATH=~/anaconda/envs/astropy27/bin/:$PATH cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON -DBOOST_ROOT=/Users/adam/anaconda/envs/astropy27/ -DMODULE=tables -DPYTHON2_LIBRARY=~/anaconda/envs/astropy27/lib -DPYTHON2_INCLUDE_DIR=~/anaconda/envs/astropy27/include
```
which resulted in the appropriate values in `CMakeCache.txt`

Error:
```
In file included from /Users/adam/anaconda/envs/astropy27/include/boost/python/detail/prefix.hpp:13:0,
                 from /Users/adam/anaconda/envs/astropy27/include/boost/python/args.hpp:8,
                 from /Users/adam/anaconda/envs/astropy27/include/boost/python.hpp:11,
                 from /Users/adam/repos/casacore/casacore/python/Converters/PycArray.h:34,
                 from /Users/adam/repos/casacore/casacore/python/Converters/PycArray.tcc:31,
                 from /Users/adam/repos/casacore/python/Converters/PycArray.cc:30:
/Users/adam/anaconda/envs/astropy27/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                       ^
compilation terminated.
make[2]: *** [python/CMakeFiles/casa_python.dir/Converters/PycArray.cc.o] Error 1
make[1]: *** [python/CMakeFiles/casa_python.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by keflavich** [comment]
and for the record, `pyconfig.h` exists and is I think where it should be:
```
cyg ~/repos/casacore/build master$ ls /Users/adam/anaconda/envs/astropy27//include/python2.7/pyconfig.h
/Users/adam/anaconda/envs/astropy27//include/python2.7/pyconfig.h
```

**Comment by tammojan** [comment]
You could check `CMakeCache.txt` for `PYTHON2_INCLUDE_DIR` (my guess is that this is set to `/usr/include` while it should point to `~/anaconda/...`

Specifying `-DPYTHON2_EXECUTABLE=~/anaconda/envs/astropy27/bin/python` should work, the prefix of this path is used for searching for the include files.

As a quick fix, you could just set `CPATH=~/anaconda/envs/astropy27/include/:$CPATH` to make the compiler look in this directory for header files.

**Comment by keflavich** [comment]
Unfortunately it looks like `PYTHON2_INCLUDE_DIR` is set correctly:
```
//Python2 include folder
PYTHON2_INCLUDE_DIR:PATH=/Users/adam/anaconda/envs/astropy27/include
//Path to Python2 interpreter
PYTHON2_EXECUTABLE:FILEPATH=/Users/adam/anaconda/envs/astropy27/bin/python2
```
I'll try the `CPATH` approach though:
```
CPATH=~/anaconda/envs/astropy27/include/:$CPATH PATH=~/anaconda/envs/astropy27/bin/:$PATH cmake .. -DUSE_FFTW3=ON -DUSE_HDF5=ON -DBUILD_PYTHON=ON -DUSE_THREADS=ON -DUSE_OPENMP=ON -DBOOST_ROOT=/Users/adam/anaconda/envs/astropy27/ -DMODULE=tables -DPYTHON2_LIBRARY=~/anaconda/envs/astropy27/lib -DPYTHON2_INCLUDE_DIR=~/anaconda/envs/astropy27/include
```

**Comment by keflavich** [comment]
still fails:
```
In file included from /Users/adam/anaconda/envs/astropy27/include/boost/python/detail/prefix.hpp:13:0,
                 from /Users/adam/anaconda/envs/astropy27/include/boost/python/args.hpp:8,
                 from /Users/adam/anaconda/envs/astropy27/include/boost/python.hpp:11,
                 from /Users/adam/repos/casacore/casacore/python/Converters/PycArray.h:34,
                 from /Users/adam/repos/casacore/casacore/python/Converters/PycArray.tcc:31,
                 from /Users/adam/repos/casacore/python/Converters/PycArray.cc:30:
/Users/adam/anaconda/envs/astropy27/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                       ^
compilation terminated.
make[2]: *** [python/CMakeFiles/casa_python.dir/Converters/PycArray.cc.o] Error 1
make[1]: *** [python/CMakeFiles/casa_python.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tammojan** [comment]
I've reproduced your error on my system, will try to fix it. Let me know if you make progress yourself.

**Comment by tammojan** [comment]
### The problem

The problem seems to be that `boost-python` that comes with anaconda is compiled against `libstdc++` while the default on MacOS is `libc++`. Casacore on macOS also uses `libc++`. The two libraries are not fully compatible. The actual error is that in `tConvert.cc.o` the following symbol is used:
```
boost::python::objects::register_dynamic_id_aux(boost::python::type_info, std::__1::pair<void*, boost::python::type_info> (*)(void*))
```
while in the Anaconda-provided boost-python the following symbol is defined:
```
boost::python::objects::register_dynamic_id_aux(boost::python::type_info, std::pair<void*, boost::python::type_info> (*)(void*))
```

### A solution
A solution is to install boost-python from source with `libc++`. Alternatively, the conda package [Boost Mac](https://anaconda.org/salilab/boost-mac) might help, I haven't tried. Below are instructions for installing boost-python in two conda environments:

Make sure these environments do not contain boost:
- `conda uninstall -n astropy27 boost`
- `conda uninstall -n astropy36 boost`
Download boost
- `mkdir tmp && cd tmp`
- Download boost source package (`.tar.gz`) from https://dl.bintray.com/boostorg/release/1.64.0/source/

Install boost in 2.7 environment
- `tar xf boost_1_64_0.tar.gz && cd boost_1_64_0`
- `source activate astropy27` # Not sure this is needed but it doesn't hurt
- `./bootstrap.sh --prefix=/anaconda/envs/astropy27/ --with-python-root=/anaconda/envs/astropy27/ --with-libraries=python`
- `./b2 -j3`
- `./b2 -install -j3`

Remove boost install directory to forget about the 2.6 locations:
- `cd .. && rm -r boost_1_64_0`

Install boost in 3.6 environment:
- `tar xf boost_1_64_0.tar.gz && cd boost_1_64_0`
- `source activate astropy36` # Not sure this is needed but it doesn't hurt
- `export CPATH=/anaconda/envs/astropy36/include/python3.6m:$CPATH`
- `./b2 -j3`
- `./b2 install -j3`

Now, to configure casacore, a slight modification is needed to deal with two Boosts. Edit https://github.com/casacore/casacore/blob/master/python3/CMakeLists.txt#L24 to add the following line around line 24:
```
set (BOOST_ROOT ${PYTHON3_BOOST_ROOT})
```

Now do the casacore setup:
- `source activate astropy27` # not sure this is needed but it doesn't hurt
- `cmake -DBUILD_PYTHON3=On -DPYTHON3_BOOST_ROOT=/anaconda/envs/astropy36/ -DPYTHON3_EXECUTABLE=/anaconda/envs/astropy36/bin/python -DBUILD_PYTHON=On -DBOOST_ROOT=/anaconda/envs/astropy27 -DPYTHON2_EXECUTABLE=/anaconda/envs/astropy27/bin/python ../../src/`

Check the output of CMake, check that the 2s and 3s line up
```
-- PYTHON2_EXECUTABLE ......... = /anaconda/envs/astropy27/bin/python
-- PYTHON2_LIBRARIES........... = /anaconda/envs/astropy27/lib/libpython2.7.dylib
-- PYTHON2_NUMPY_INCLUDE_DIRS . = /anaconda/envs/astropy27/lib/pytho
-- PYTHON2_Boost_LIBRARIES .... = /anaconda/envs/astropy27/lib/libboost_python.dylib
-- PYTHON2_Boost_INCLUDE_DIRS . = /anaconda/envs/astropy27/include
-- PYTHON3_EXECUTABLE ......... = /anaconda/envs/astropy36/bin/python
-- PYTHON3_LIBRARIES .......... = /anaconda/envs/astropy36/lib/libpython3.6m.dylib
-- PYTHON3_NUMPY_INCLUDE_DIRS . = /anaconda/envs/astropy36/lib/python3.6/site-packages/numpy/core/include
-- PYTHON3_Boost_LIBRARIES .... = /anaconda/envs/astropy36/lib/libboost_python3.dylib
-- PYTHON3_Boost_INCLUDE_DIRS . = /anaconda/envs/astropy27/include
```

Now casacore should build.
