### ISSUE TITLE
measuresdata-update throws exception

### ISSUE THREAD

**Issue by gijzelaerr** [casacore/casacore#814]
on current master:
```
$ measuresdata-update
Calling measuresdata

Create data tables for Measures
-----------------------------------------------
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)
Severe error calling measuresdata with
```

**Comment by dpetry** [comment]
What version of measuresdata-update and underlying casacore is used by ASTRON for production?
Can you do a diff with that production version to see what may be causing the problem?
Also, is it certain that this is really a problem with the code rather than a problem with the setup of how the update is run?

**Comment by sabourke** [comment]
It's not a problem with the setup of how the update is run. It seems to crash in all circumstances. Conversely when compiled and linked against the stock ubuntu 18.04 casacore it works fine. I.E. it looks like the problem is not in measuresdata but rather some interface changed in casacore.

**Comment by sabourke** [comment]
This is a specific example of the more general issue #815 and @rtobar's info there solves this. I.E. linking with libpthread fixes the issue.

**Comment by tammojan** [comment]
@gijzelaerr Could you try measuresdata-update while building with `-DUSE_THREADS=On`?

**Comment by gijzelaerr** [comment]
this issue is a duplicate of https://github.com/casacore/casacore/issues/815
