### ISSUE TITLE
Unknown error -1

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#815]
As mentioned in #814, on some systems (not travis), all built binaries crash with 'unknown error -1'. For example on astron CEP3. This is a showstopper for release 3.0.

**Comment by gervandiepen** [comment]
Let's take a look on it on Monday. Can you build them in debug mode and see
if they fail as well?

**Comment by rtobar** [comment]
I also experienced the same problem with a build with gcc 6.3 and then with 5.4 as well. In these situations lots of unit tests actually fail due to this reason. I used the first failure as an example:

```
[rtobar@sorrento build_3.0.0]---> ./casa/Arrays/test/tArrayIO3 < ./casa/Arrays/test/tArrayIO3.in 
Input Array [1 2 3 4 5 6] 
--------------------------------------
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)
```

Reading online, it seems that a common diagnose is that final binaries do not reference the threading library, which is required by ``std::call_once`` calls. I thus manually tried it out
(mind the final ``-pthread``):

```
[rtobar@sorrento build_3.0.0]---> /usr/bin/c++ -fno-threadsafe-statics -fcx-fortran-rules
-Wextra -Wall -W -Wpointer-arith -Woverloaded-virtual -Wwrite-strings
-pedantic -Wno-long-long -fsigned-char -std=c++11 -g   casa/Arrays/test/CMakeFiles/tArrayIO3.dir/tArrayIO3.cc.o
-o casa/Arrays/test/tArrayIO3 -rdynamic casa/libcasa_casa.so.3 -lreadline
-lncurses -ldl -Wl,-rpath,/home/rtobar/scm/git/casacore/build_3.0.0/casa
-pthread
[rtobar@sorrento build_3.0.0]---> ./casa/Arrays/test/tArrayIO3 < ./casa/Arrays/test/tArrayIO3.in 
Input Array [1 2 3 4 5 6] 
--------------------------------------
[1, 2, 3, 4, 5, 6]
<rest of the output>
```

Linkage to the thread library happens in ``CMakeLists.txt`` only with ``USE_THREADS=ON`` (which is off by default), so that explains why some builds are affected and some are not. I'd assume that moving the pthread-related cmake code out of the ``if (USE_THREADS)`` block should make things right, but there might be other considerations that I'm not aware of, so I'm not proposing a patch for this.

BTW, at least in cmake 3 there is a [FindThreads](https://cmake.org/cmake/help/v3.0/module/FindThreads.html) module that sets the ``CMAKE_THREAD_LIBS_INIT`` to the appropriate linking flag depending on the compiler/system. I don't know if that's available in 2.6, but it might be worth a look to avoid having to maintain the compiler-specific bits in that part of the ``CMakeLists.txt``.

**Comment by sabourke** [comment]
@tammojan you mean #814

**Comment by gijzelaerr** [comment]
compiling with `USE_THREADS=on` seems to solve the issue.
