### ISSUE TITLE
variance for complex number

### ISSUE THREAD

**Issue by revoltek** [casacore/casacore#842]
Since visibilities are complex numbers it would be nice to add the variance of complex number in taql. The implementation should follow this equation:
https://en.wikipedia.org/wiki/Complex_random_variable#Variance

this would avoid the error:
 Error in select expression: Erroneous use of function gvariance - invalid operand data type; function argument is not real

which for example doesn't happen with the "mean"

**Comment by revoltek** [comment]
What about just setting it to the square root of the variance?

**Comment by gervandiepen** [comment]
Note that you can already get the variance of a complex number, since it is equal to the sum of the variances of the real and imaginary parts, thus in TaQL:
     variance(real(DATA)) + variance(imag(DATA))

But I'll add support for Complex, because the way above is about 4x slower than a direct implementation.
I'll also add it for avdev and stddev.

**Comment by revoltek** [comment]
many thanks for the workaround!

**Comment by gervandiepen** [comment]
Implemented in PR #851.
