### ISSUE TITLE
Finding NumPy works with old cmake, fails with new cmake

### ISSUE THREAD

**Issue by tammojan** [casacore/casacore#939]
This was probably introduced by #922.

```
> cmake --version
cmake version 3.12.3
> cmake .
[...]
-- Looking for python2 specific environment...
CMake Error at /home/dijkema/opt/cmake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Python2 (missing: NumPy) (found version "2.7.5")
Call Stack (most recent call first):
  /home/dijkema/opt/cmake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/dijkema/opt/cmake/share/cmake-3.12/Modules/FindPython/Support.cmake:795 (find_package_handle_standard_args)
  /home/dijkema/opt/cmake/share/cmake-3.12/Modules/FindPython2.cmake:138 (include)
  python/CMakeLists-cmake3.12.txt:3 (find_package)
  python/CMakeLists.txt:4 (include)
```

With old cmake (same build directory, same system (lhd001 on CEP3, CentOS 7):
```
> cmake --version
cmake version 2.8.12.2
> cmake .
[...]
-- PYTHON2_EXECUTABLE ......... = /usr/bin/python2
-- PYTHON2_LIBRARIES........... = /usr/lib64/libpython2.7.so
-- PYTHON2_NUMPY_INCLUDE_DIRS . = /usr/lib64/python2.7/site-packages/numpy/core/include
-- PYTHON2_Boost_LIBRARIES .... = /usr/lib64/libboost_python-mt.so
-- PYTHON2_Boost_INCLUDE_DIRS . = /usr/include
```

**Comment by rtobar** [comment]
We saw this also here, but forgot to notify about it.

I think the issue is that NumPy is looked for as a `COMPONENT` of the [Python3 package](https://github.com/casacore/casacore/blob/master/python3/CMakeLists-cmake3.12.txt#L3), which is something that appeared only in 3.14 (you can see it in the [3.14 documentation](https://cmake.org/cmake/help/v3.14/module/FindPython3.html) but not [in 3.13](https://cmake.org/cmake/help/v3.13/module/FindPython3.html)). However, the cmake version check performed in the parent file is [checking for 3.12+](https://github.com/casacore/casacore/blob/master/python3/CMakeLists.txt#L3)
